"""Stage 7 — Deploy & Maintain.

For CODE tickets: open a real GitHub PR with the receipts as the body
(or print the gh command if dry_run). For SIMPLE tickets: write the
drafted email to .demo/outputs/. Both: log a monitoring breadcrumb to
Redis (the standby Blaxel sandbox is mentioned in the receipts but not
literally created).
"""

from __future__ import annotations

import shlex
import subprocess
import tempfile
from pathlib import Path

from agent_mes.interfaces import RedisMemoryProtocol
from agent_mes.schema import Artifact, MESTask, StageEnum, StageEvent, TicketType
from agent_mes.stages.base import BaseStage

OUTPUTS_DIR = Path(".demo/outputs")


class DeployStage(BaseStage):
    STAGE = StageEnum.DEPLOY
    AGENT = "GitHub+Blaxel+Redis"

    def __init__(
        self,
        redis: RedisMemoryProtocol,
        github_repo: str = "benikigai/agent-mes",
        dry_run: bool = False,
    ) -> None:
        self.redis = redis
        self.github_repo = github_repo
        self.dry_run = dry_run
        OUTPUTS_DIR.mkdir(parents=True, exist_ok=True)

    async def execute(self, task: MESTask) -> list[StageEvent]:
        task.current_stage = StageEnum.DEPLOY

        if task.type == TicketType.CODE:
            event = await self._deploy_code(task)
        else:
            event = await self._deploy_email(task)

        # Log a monitoring breadcrumb (Blaxel standby + Redis log)
        await self.redis.write_lesson(
            text=f"deploy event for {task.id}: {task.intent}",
            topics=["deploy", "monitoring"],
            user_id=task.requester,
        )

        task.status = "merged"
        return [event]

    async def _deploy_code(self, task: MESTask) -> StageEvent:
        body = self._render_pr_body(task)

        if self.dry_run:
            ref = f"(dry-run) gh pr create --title 'AgentMES: {task.intent[:40]}'"
            return self._emit_event(
                task=task,
                agent="GitHub",
                action="PR opened (dry-run)",
                metadata={"pr_url": ref, "standby": "blaxel", "status": "PASS"},
                artifacts=[Artifact(type="pr", ref=ref, summary="dry-run only")],
            )

        with tempfile.NamedTemporaryFile(mode="w", suffix=".md", delete=False) as f:
            f.write(body)
            body_path = f.name

        try:
            result = subprocess.run(
                [
                    "gh",
                    "pr",
                    "create",
                    "--repo",
                    self.github_repo,
                    "--title",
                    f"AgentMES: {task.intent[:60]}",
                    "--body-file",
                    body_path,
                ],
                capture_output=True,
                text=True,
                timeout=30,
            )
            pr_url = result.stdout.strip() if result.returncode == 0 else f"(failed: {result.stderr[:80]})"
        except Exception as e:
            pr_url = f"(error: {e})"
        finally:
            Path(body_path).unlink(missing_ok=True)

        return self._emit_event(
            task=task,
            agent="GitHub",
            action="PR opened",
            metadata={"pr_url": pr_url, "standby": "blaxel", "status": "PASS"},
            artifacts=[Artifact(type="pr", ref=pr_url, summary="real PR")],
        )

    async def _deploy_email(self, task: MESTask) -> StageEvent:
        body = task.context_bundle.get("email_body", "(no body)")
        out_path = OUTPUTS_DIR / f"email-{task.id}.md"
        out_path.write_text(body)
        return self._emit_event(
            task=task,
            agent="file",
            action=f"saved email to {out_path}",
            metadata={"would_send": "via SMTP", "status": "PASS"},
            artifacts=[Artifact(type="email", ref=str(out_path), summary="drafted")],
        )

    def _render_pr_body(self, task: MESTask) -> str:
        lines = [
            f"# AgentMES: {task.intent}",
            "",
            f"**Ticket:** {task.id}",
            f"**Requester:** {task.requester}",
            f"**Source:** {task.source}",
            "",
            "## Receipts (auto-generated by AgentMES)",
            "",
        ]
        for ev in task.events:
            lines.append(f"- **[{ev.stage.value}]** `{ev.agent}` — {ev.action}")
        lines.append("")
        lines.append("---")
        lines.append("Generated by AgentMES — 7-stage AI-native engineering pipeline.")
        return "\n".join(lines)
